name: simplesite
services:
  - name: web
    environment_slug: node-js
    source_dir: /
    build_command: npm run build
    output_dir: dist
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    github:
      repo: emiranda04/simplesite
      branch: main
      deploy_on_push: true
