name: simplesite
region: nyc # or your preferred region
static_sites:
  - name: web
    github:
      repo: emiranda04/simplesite
      branch: main
    source_dir: /
    output_dir: dist
    build_command: bash scripts/build.bash
