name: Build with Docker, Deploy as Static Site

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build static files using Docker
        run: |
          # Use a Node.js Docker container to build your site
          docker run --rm -v $(pwd):/app -w /app node:18-alpine \
            sh -c "npm install && npx tailwindcss -i ./src/styles/input.css -o ./dist/styles/output.css --minify && cp src/*.html dist/"

      - name: Verify built files
        run: |
          ls -la dist/
          echo "Build completed successfully!"

      - name: Deploy to Digital Ocean Apps
        uses: digitalocean/app_action@v1
        with:
          app_name: seahorse-app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}